### ISSUE TITLE
$invoice->addOnAmount() does not pay attention to the quantity of AddOns

### ISSUE THREAD

**Issue by Mittler1** [laravel/cashier-braintree#71]
As the title suggests, the function does not pay attention to the quantity of addons:
```
    /**
     * Get the raw add-on amount.
     *
     * @return float
     */
    public function addOnAmount()
    {
        $totalAddOn = 0;

        foreach ($this->transaction->addOns as $addOn) {
            $totalAddOn += $addOn->amount;
        }

        return (float) $totalAddOn;
    }
```

should be something like

```
        foreach ($this->transaction->addOns as $addOn) {
            $totalAddOn += $addOn->amount * $addOn->quantity;
        }
```

**Comment by driesvints** [comment]
Hmm. I *think* you're correct but my underlying knowledge of Braintree is too limited to be sure. Can you provide **a practical example** which demonstrates this?

**Comment by Mittler1** [comment]
Yes, I do it with pleasure. I recently had exactly this Issue with my own project.

In my project, I needed a rule like _"per user per month"_. By default, Cashier-Braintree can not do this, unlike Stripe, because Braintree does not allow multiple subscription to one plan. That's why I used AddOns for that.

For example, an account has a base subscription costing $10 per month and includes one user. Additional users can be booked through the _"additional_user"_ AddOn for $8 per additional user per month.

The code is just like this:
```
// first subscribe account to the default plan
$account->newSubscription('base_plan', 'base_plan')->create($nonceFromTheClient);
```

```
// add addOn "additional_user" for example 5 times to subscription
$subscription = $account->subscription('base_plan');
$subscription->asBraintreeSubscription()->update($subscription->braintree_id, [
    'addOns' => [
        'add' => [
            [
                'inheritedFromId' => 'additional_user',
                'quantity'  => 5
            ]
        ]
    ]
]);
```

Now the account has a basic subscription with one user included for $10 plus five times the "additional_user" AddOn for $8 each.

Now, if I want to automatically generate an invoice for the account, the charge is about $50 which is correct. But the amount of the AddOns will be displayed as $8 instead of $40:

```
$account->findInvoice($invoice)->addOnAmount();
// returns 8
```

That's because addOnAmount() will always return $8, no matter how many times the AddOn was actually purchased.

**Comment by driesvints** [comment]
Thanks for all the feedback! I've pushed some commits which should fix this. Will be released in a patch next Tuesday. Thanks for reporting.

**Comment by Mittler1** [comment]
Thank You! I am glad that I could contribute to Cashier.
