### ISSUE TITLE
ready for SCA?

### ISSUE THREAD

**Issue by eXorus** [laravel/cashier-braintree#75]
As of right now, the enforcement date for Strong Consumer Authentication (SCA) is less than 3 months away. Is cahier ready?

3D Secure 2.0 SDKs are now available in braintree production.

Docs: https://developers.braintreepayments.com/guides/3d-secure/migration/javascript/v3

https://braintreepayments.docs.contently.com/v/an-overview-of-psd2-strong-customer-authentication-requirements-and-3d-secure-2

Thanks for your hard work on cashier stripe. I'm using braintree with spark for my business.

**Comment by driesvints** [comment]
Unfortunately, we're not planning on updating cashier-braintree for SCA. However, the main Cashier library for Stripe will be ready. It's probably best that you start using the Braintree SDK directly if you want your app to be SCA compliant.

**Comment by eXorus** [comment]
Thanks @driesvints 

So my business that works with Laravel Spark will failed in september? all my subscriptions will be canceled?

It could be great to have an idea of the supported status for all the laravel ecosystem.
- Laravel Spark 5.0: deprecated ...
- Lumen: end of life except for security fix ...
- cashier braintree: not maintained ...

Something like https://laravel.com/docs/releases#support-policy.

**Comment by driesvints** [comment]
> So my business that works with Laravel Spark will failed in september? all my subscriptions will be canceled?

No, SCA won't apply for existing subscriptions. But you'll have to update the Braintree implementation for any new ones. See Stripe's confirmation on this here: https://twitter.com/stripe/status/1149304278563074048

> It could be great to have an idea of the supported status for all the laravel ecosystem.

I agree we can do better here. I've already sent in a PR to the Spark docs to clarify the support policy: https://github.com/laravel/spark-docs/pull/53

For Lumen we haven't taken a decision yet on what we're going to do. Cashier Braintree as well but it seems likely we won't be supporting it much longer.

**Comment by eXorus** [comment]
Great news for existing subscriptions.

I don't like 😞 your answer because I will have to migrate my Spark and change my payment provider.

But I ❤️ your answer and the time you take to respond to me.

Good job

**Comment by driesvints** [comment]
@eXorus you can always fork the cashier-braintree library and make the necessary changes yourself. Then link to that library in your current Spark. Maybe you need to make changes to Spark itself as well.

We just announced on Twitter that we'll be abandoning support for cashier-braintree.
